apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hbd
  name: hbd
  namespace: adeola-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbd
  strategy: {}
  template:
    metadata:
      labels:
        app: hbd
    spec:
      containers:
      - image: IMAGE_NAME
        name: hbd
        ports: 
        - containerPort: 80
        resources: {}
status: {}